import { expect } from 'chai';
import { assert } from 'chai';
import { describe } from 'mocha';
import { JsTypeCommander } from '../dist/JsTypeCommander';
import { log, error, debug } from 'util';
import { truncate } from 'fs';
import * as TL from './testLib';

describe("Testing type conversion functions", function() {
    let functionTypeGroups: TL.IFunctionTypeGroup[] = [
        TL.functionTypeGroup('string conversion',
            TL.testFunction(JsTypeCommander.asString, 'asString', '(obj?: TDefined): Nilable<string>, ifWhitespace?: boolean): Nilable<string>',
                TL.expectIsA('undefined',
                    TL.argSet(() => [undefined], 'undefined'),
                    TL.argSet(() => [undefined, undefined], 'undefined, undefined')
                ),
                TL.expectIsA('null',
                    TL.argSet(() => [null], 'null'),
                    TL.argSet(() => [undefined, null], 'undefined, null'),
                    TL.argSet(() => [null, undefined], 'null, undefined')
                ),
                TL.expectEqualTo('""', () => "",
                    TL.argSet(() => [""], '""'),
                    TL.argSet(() => [""], '""'),
                    TL.argSet(() => [[]], '[]'),
                    TL.argSet(() => [[""]], '[""]'),
                    TL.argSet(() => ["", undefined], '"", undefined'),
                    TL.argSet(() => ["", null], '"", null'),
                    TL.argSet(() => [undefined, ""], 'undefined, ""'),
                    TL.argSet(() => [null, ""], 'null, ""'),
                    TL.argSet(() => ["", Symbol.iterator], '"", Symbol.iterator'),
                    TL.argSet(() => ["", Symbol.iterator, false], '"", Symbol.iterator, false'),
                    TL.argSet(() => ["", "\t\n\r "], '"", "\\t\\n\\r "'),
                    TL.argSet(() => ["", "\t\n\r ", false], '"", "\\t\\n\\r ", false')
                ),
                TL.expectEqualTo('"true"', () => "true",
                    TL.argSet(() => ["true"], '"true"'),
                    TL.argSet(() => [true,], 'true')
                ),
                TL.expectEqualTo('"false"', () => "false",
                    TL.argSet(() => ["false"], '"false"'),
                    TL.argSet(() => [false,], 'false')
                ),
                TL.expectEqualTo('"iterator"', () => "iterator",
                    TL.argSet(() => [Symbol.iterator], 'Symbol.iterator'),
                    TL.argSet(() => [[Symbol.iterator]], '[Symbol.iterator]'),
                    TL.argSet(() => [undefined, Symbol.iterator], 'undefined, Symbol.iterator'),
                    TL.argSet(() => [null, Symbol.iterator], 'null, Symbol.iterator'),
                    TL.argSet(() => ["", Symbol.iterator, true], '"", Symbol.iterator, true'),
                    TL.argSet(() => ["\t\n\r ", Symbol.iterator, true], '"\\t\\n\\r ", Symbol.iterator, true')
                ),
                TL.expectEqualTo('"\\t\\n\\r "', () => "\t\n\r ",
                    TL.argSet(() => ["\t\n\r ", " "], '"\\t\\n\\r ", " "'),
                    TL.argSet(() => ["\t\n\r ", " "], '"\\t\\n\\r ", " "'),
                    TL.argSet(() => ["\t\n\r ", Symbol.iterator], '"\\t\\n\\r ", Symbol.iterator'),
                    TL.argSet(() => ["", "\t\n\r ", true], '"", "\\t\\n\\r ", true'),
                    TL.argSet(() => ["\t\n\r ", "", true], '"\\t\\n\\r ", "", true'),
                    TL.argSet(() => ["\t\n\r ", Symbol.iterator, false], '"\\t\\n\\r ", Symbol.iterator, false')
                )
            ),
            TL.testFunction(JsTypeCommander.toString, 'toString', '(obj?: TDefined): Nilable<string>, ifWhitespace?: boolean): string',
                TL.expectEqualTo('""', () => "",
                    TL.argSet(() => [undefined], 'undefined'),
                    TL.argSet(() => [undefined, undefined], 'undefined, undefined'),
                    TL.argSet(() => [null], 'null'),
                    TL.argSet(() => [undefined, null], 'undefined, null'),
                    TL.argSet(() => [null, undefined], 'null, undefined'),
                    TL.argSet(() => [""], '""'),
                    TL.argSet(() => [""], '""'),
                    TL.argSet(() => [[]], '[]'),
                    TL.argSet(() => [[""]], '[""]'),
                    TL.argSet(() => ["", undefined], '"", undefined'),
                    TL.argSet(() => ["", null], '"", null'),
                    TL.argSet(() => [undefined, ""], 'undefined, ""'),
                    TL.argSet(() => [null, ""], 'null, ""'),
                    TL.argSet(() => ["", Symbol.iterator], '"", Symbol.iterator'),
                    TL.argSet(() => ["", Symbol.iterator, false], '"", Symbol.iterator, false'),
                    TL.argSet(() => ["", "\t\n\r "], '"", "\\t\\n\\r "'),
                    TL.argSet(() => ["", "\t\n\r ", false], '"", "\\t\\n\\r ", false')
                ),
                TL.expectEqualTo('"true"', () => "true",
                    TL.argSet(() => ["true"], '"true"'),
                    TL.argSet(() => [true,], 'true')
                ),
                TL.expectEqualTo('"false"', () => "false",
                    TL.argSet(() => ["false"], '"false"'),
                    TL.argSet(() => [false,], 'false')
                ),
                TL.expectEqualTo('"iterator"', () => "iterator",
                    TL.argSet(() => [Symbol.iterator], 'Symbol.iterator'),
                    TL.argSet(() => [[Symbol.iterator]], '[Symbol.iterator]'),
                    TL.argSet(() => [undefined, Symbol.iterator], 'undefined, Symbol.iterator'),
                    TL.argSet(() => [null, Symbol.iterator], 'null, Symbol.iterator'),
                    TL.argSet(() => ["", Symbol.iterator, true], '"", Symbol.iterator, true'),
                    TL.argSet(() => ["\t\n\r ", Symbol.iterator, true], '"\\t\\n\\r ", Symbol.iterator, true')
                ),
                TL.expectEqualTo('"\\t\\n\\r "', () => "\t\n\r ",
                    TL.argSet(() => ["\t\n\r ", " "], '"\\t\\n\\r ", " "'),
                    TL.argSet(() => ["\t\n\r ", " "], '"\\t\\n\\r ", " "'),
                    TL.argSet(() => ["\t\n\r ", Symbol.iterator], '"\\t\\n\\r ", Symbol.iterator'),
                    TL.argSet(() => ["", "\t\n\r ", true], '"", "\\t\\n\\r ", true'),
                    TL.argSet(() => ["\t\n\r ", "", true], '"\\t\\n\\r ", "", true'),
                    TL.argSet(() => ["\t\n\r ", Symbol.iterator, false], '"\\t\\n\\r ", Symbol.iterator, false')
                )
            )
        ),
        TL.functionTypeGroup('boolean conversion',
            TL.testFunction(JsTypeCommander.asBoolean, 'asBoolean', '(obj?: TDefined): Nilable<boolean>): Nilable<boolean>',
                TL.expectIsA('undefined',
                    TL.argSet(() => [undefined], 'undefined'),
                    TL.argSet(() => [""], '""'), TL.argSet(() => ["talse"], '"talse"'), TL.argSet(() => ["nes"], '""nes'), TL.argSet(() => ["yo"], '"yo"'), TL.argSet(() => ["frue"], '"frue"'),
                    TL.argSet(() => [[]], '[]'),
                    TL.argSet(() => [undefined, undefined], 'undefined, undefined')
                ),
                TL.expectIsA('null',
                    TL.argSet(() => [null], 'null'),
                    TL.argSet(() => [undefined, null], 'undefined, null'),
                    TL.argSet(() => [null, undefined], 'null, undefined')
                ),
                TL.expectEqualTo('true', () => true,
                    TL.argSet(() => [true], 'true'),
                    TL.argSet(() => [1], '1'),
                    TL.argSet(() => [-1], '-1'),
                    TL.argSet(() => [100], '100'),
                    TL.argSet(() => [Number.POSITIVE_INFINITY], 'Number.POSITIVE_INFINITY'),
                    TL.argSet(() => [Number.NEGATIVE_INFINITY], 'Number.NEGATIVE_INFINITY'),
                    TL.argSet(() => ["t"], '"t"'), TL.argSet(() => ["T"], '"T"'),
                    TL.argSet(() => ["true"], '"true"'), TL.argSet(() => ["TRUE"], '"TRUE"'), TL.argSet(() => ["True"], '"True"'), TL.argSet(() => ["tRuE"], '"tRuE"'),
                    TL.argSet(() => ["y"], '"y"'), TL.argSet(() => ["Y"], '"Y"'),
                    TL.argSet(() => ["yes"], '"yes"'), TL.argSet(() => ["YES"], '"YES"'), TL.argSet(() => ["Yes"], '"Yes"'), TL.argSet(() => ["yEs"], '"yEs"'),
                    TL.argSet(() => [[true]], '[true]'),
                    TL.argSet(() => [true, undefined], 'true, undefined'),
                    TL.argSet(() => [true, null], 'true, null'),
                    TL.argSet(() => [undefined, true], 'undefined, true'),
                    TL.argSet(() => [null, true], 'null, true'),
                    TL.argSet(() => [null, -0.0001], 'null, -0.0001'),
                    TL.argSet(() => [true, false], 'true, false')
                ),
                TL.expectEqualTo('false', () => false,
                    TL.argSet(() => [false], 'false'),
                    TL.argSet(() => [0], '0'),
                    TL.argSet(() => ["-0.0000"], '"-0.0000"'),
                    TL.argSet(() => [NaN], 'NaN'),
                    TL.argSet(() => ["f"], '"f"'), TL.argSet(() => ["F"], '"F"'),
                    TL.argSet(() => ["false"], '"false"'), TL.argSet(() => ["FALSE"], '"FALSE"'), TL.argSet(() => ["False"], '"False"'), TL.argSet(() => ["fAlSe"], '"fAlSe"'),
                    TL.argSet(() => [[false]], '[false]'),
                    TL.argSet(() => [false, undefined], 'false, undefined'),
                    TL.argSet(() => [false, null], 'false, null'),
                    TL.argSet(() => [undefined, false], 'undefined, false'),
                    TL.argSet(() => [null, false], 'null, false'),
                    TL.argSet(() => [false, true], 'false, true')
                )
            ),
            TL.testFunction(JsTypeCommander.toBoolean, 'toBoolean', '(obj?: TDefined): Nilable<boolean>): boolean',
                TL.expectEqualTo('true', () => true,
                    TL.argSet(() => [true], 'true'),
                    TL.argSet(() => [1], '1'),
                    TL.argSet(() => [-1], '-1'),
                    TL.argSet(() => [100], '100'),
                    TL.argSet(() => [Number.POSITIVE_INFINITY], 'Number.POSITIVE_INFINITY'),
                    TL.argSet(() => [Number.NEGATIVE_INFINITY], 'Number.NEGATIVE_INFINITY'),
                    TL.argSet(() => ["t"], '"t"'), TL.argSet(() => ["T"], '"T"'),
                    TL.argSet(() => ["true"], '"true"'), TL.argSet(() => ["TRUE"], '"TRUE"'), TL.argSet(() => ["True"], '"True"'), TL.argSet(() => ["tRuE"], '"tRuE"'),
                    TL.argSet(() => ["y"], '"y"'), TL.argSet(() => ["Y"], '"Y"'),
                    TL.argSet(() => ["yes"], '"yes"'), TL.argSet(() => ["YES"], '"YES"'), TL.argSet(() => ["Yes"], '"Yes"'), TL.argSet(() => ["yEs"], '"yEs"'),
                    TL.argSet(() => [[true]], '[true]'),
                    TL.argSet(() => [true, undefined], 'true, undefined'),
                    TL.argSet(() => [true, null], 'true, null'),
                    TL.argSet(() => [undefined, true], 'undefined, true'),
                    TL.argSet(() => [null, true], 'null, true'),
                    TL.argSet(() => [null, -0.0001], 'null, -0.0001'),
                    TL.argSet(() => [true, false], 'true, false')
                ),
                TL.expectEqualTo('false', () => false,
                    TL.argSet(() => [undefined], 'undefined'),
                    TL.argSet(() => [""], '""'), TL.argSet(() => ["talse"], '"talse"'), TL.argSet(() => ["nes"], '""nes'), TL.argSet(() => ["yo"], '"yo"'), TL.argSet(() => ["frue"], '"frue"'),
                    TL.argSet(() => [[]], '[]'),
                    TL.argSet(() => [undefined, undefined], 'undefined, undefined'),
                    TL.argSet(() => [null], 'null'),
                    TL.argSet(() => [undefined, null], 'undefined, null'),
                    TL.argSet(() => [null, undefined], 'null, undefined'),
                    TL.argSet(() => [false], 'false'),
                    TL.argSet(() => [0], '0'),
                    TL.argSet(() => ["-0.0000"], '"-0.0000"'),
                    TL.argSet(() => [NaN], 'NaN'),
                    TL.argSet(() => ["f"], '"f"'), TL.argSet(() => ["F"], '"F"'),
                    TL.argSet(() => ["false"], '"false"'), TL.argSet(() => ["FALSE"], '"FALSE"'), TL.argSet(() => ["False"], '"False"'), TL.argSet(() => ["fAlSe"], '"fAlSe"'),
                    TL.argSet(() => [[false]], '[false]'),
                    TL.argSet(() => [false, undefined], 'false, undefined'),
                    TL.argSet(() => [false, null], 'false, null'),
                    TL.argSet(() => [undefined, false], 'undefined, false'),
                    TL.argSet(() => [null, false], 'null, false'),
                    TL.argSet(() => [false, true], 'false, true')
                )
            )
        ),
        TL.functionTypeGroup('number conversion',
            TL.testFunction(JsTypeCommander.asNumber, 'asNumber', '(obj?: TDefined): Nilable<number>): Nilable<number>',
                TL.expectIsA('undefined',
                    TL.argSet(() => [undefined], 'undefined'),
                    TL.argSet(() => [""], '""'),
                    TL.argSet(() => [[]], '[]'),
                    TL.argSet(() => [undefined, undefined], 'undefined, undefined')
                ),
                TL.expectIsA('null',
                    TL.argSet(() => [null], 'null'),
                    TL.argSet(() => [undefined, null], 'undefined, null'),
                    TL.argSet(() => [null, undefined], 'null, undefined')
                ),
                TL.expectEqualTo('1', () => 1,
                    TL.argSet(() => [1], '1'),
                    TL.argSet(() => [true], 'true'),
                    TL.argSet(() => ["1"], '"1"'),
                    TL.argSet(() => ["0001.00"], '"0001.00"'),
                    TL.argSet(() => [undefined, 1], 'undefined, 1'),
                    TL.argSet(() => [undefined, true], 'undefined, true'),
                    TL.argSet(() => [undefined, "1"], 'undefined, "1"'),
                    TL.argSet(() => [undefined, "0001.00"], 'undefined, "0001.00"'),
                    TL.argSet(() => [null, 1], 'null, 1'),
                    TL.argSet(() => [null, true], 'null, true'),
                    TL.argSet(() => [null, "1"], 'null, "1"'),
                    TL.argSet(() => [null, "0001.00"], 'null, "0001.00"'),
                    TL.argSet(() => ["x2", 1], '"x2", 1'),
                    TL.argSet(() => ["x2", true], '"x2", true'),
                    TL.argSet(() => [null, "1"], 'null, "1"'),
                    TL.argSet(() => [null, "0001.00"], 'null, "0001.00"')
                ),
                TL.expectEqualTo('0', () => 0,
                    TL.argSet(() => [0], '0'),
                    TL.argSet(() => ["0"], '"0"'),
                    TL.argSet(() => ["+0"], '"+0"'),
                    TL.argSet(() => [false], 'false'),
                    TL.argSet(() => ["-0.0000"], '"-0.0000"'),
                    //TL.argSet(() => ["false"], '"false"'),
                    //TL.argSet(() => [[false]], '[false]'),
                    TL.argSet(() => [false, undefined], 'false, undefined'),
                    TL.argSet(() => [false, null], 'false, null'),
                    TL.argSet(() => [undefined, false], 'undefined, false'),
                    TL.argSet(() => [null, false], 'null, false'),
                    TL.argSet(() => [false, true], 'false, true')
                ),
                TL.expectEqualTo('100', () => 100,
                    TL.argSet(() => [100], '100'),
                    TL.argSet(() => ["100"], '"100"'),
                    TL.argSet(() => ["+00100.0000"], '"+00100.0000"')
                ),
                TL.expectEqualTo('-100.0001', () => -100.0001,
                    TL.argSet(() => [-100.0001], '-100.0001'),
                    TL.argSet(() => ["-100.0001"], '"-100.0001"'),
                    TL.argSet(() => ["-00100.000100"], '"-00100.000100"')
                ),
                TL.expectEqualTo('0.0001', () => 0.0001,
                    TL.argSet(() => [0.0001], '0.0001'),
                    TL.argSet(() => ["0.0001"], '"0.0001"'),
                    TL.argSet(() => ["+00000.000100"], '"+00000.000100"')
                )
            ),
            TL.testFunction(JsTypeCommander.toNumber, 'toNumber', '(obj?: TDefined): Nilable<number>): number',
                TL.expectEqualTo('0', () => 0,
                    TL.argSet(() => [undefined], 'undefined'),
                    TL.argSet(() => [""], '""'),
                    TL.argSet(() => [[]], '[]'),
                    TL.argSet(() => [undefined, undefined], 'undefined, undefined'),
                    TL.argSet(() => [null], 'null'),
                    TL.argSet(() => [undefined, null], 'undefined, null'),
                    TL.argSet(() => [null, undefined], 'null, undefined'),
                    TL.argSet(() => [0], '0'),
                    TL.argSet(() => ["0"], '"0"'),
                    TL.argSet(() => ["+0"], '"+0"'),
                    TL.argSet(() => [false], 'false'),
                    TL.argSet(() => ["-0.0000"], '"-0.0000"'),
                    TL.argSet(() => ["false"], '"false"'),
                    //TL.argSet(() => [[false]], '[false]'),
                    TL.argSet(() => [false, undefined], 'false, undefined'),
                    TL.argSet(() => [false, null], 'false, null'),
                    TL.argSet(() => [undefined, false], 'undefined, false'),
                    TL.argSet(() => [null, false], 'null, false'),
                    TL.argSet(() => [false, true], 'false, true')
                ),
                TL.expectEqualTo('1', () => 1,
                    TL.argSet(() => [1], '1'),
                    TL.argSet(() => [true], 'true'),
                    TL.argSet(() => ["1"], '"1"'),
                    TL.argSet(() => ["0001.00"], '"0001.00"'),
                    TL.argSet(() => [undefined, 1], 'undefined, 1'),
                    TL.argSet(() => [undefined, true], 'undefined, true'),
                    TL.argSet(() => [undefined, "1"], 'undefined, "1"'),
                    TL.argSet(() => [undefined, "0001.00"], 'undefined, "0001.00"'),
                    TL.argSet(() => [null, 1], 'null, 1'),
                    TL.argSet(() => [null, true], 'null, true'),
                    TL.argSet(() => [null, "1"], 'null, "1"'),
                    TL.argSet(() => [null, "0001.00"], 'null, "0001.00"'),
                    TL.argSet(() => ["x2", 1], '"x2", 1'),
                    TL.argSet(() => ["x2", true], '"x2", true'),
                    TL.argSet(() => [null, "1"], 'null, "1"'),
                    TL.argSet(() => [null, "0001.00"], 'null, "0001.00"')
                ),
                TL.expectEqualTo('100', () => 100,
                    TL.argSet(() => [100], '100'),
                    TL.argSet(() => ["100"], '"100"'),
                    TL.argSet(() => ["+00100.0000"], '"+00100.0000"')
                ),
                TL.expectEqualTo('-100.0001', () => -100.0001,
                    TL.argSet(() => [-100.0001], '-100.0001'),
                    TL.argSet(() => ["-100.0001"], '"-100.0001"'),
                    TL.argSet(() => ["-00100.000100"], '"-00100.000100"')
                ),
                TL.expectEqualTo('0.0001', () => 0.0001,
                    TL.argSet(() => [0.0001], '0.0001'),
                    TL.argSet(() => ["0.0001"], '"0.0001"'),
                    TL.argSet(() => ["+00000.000100"], '"+00000.000100"')
                )
            )
        )
    ];
    TL.describeFunctionTypeGroups(functionTypeGroups);
    describe("Testing function toArray(obj?: TDefined, checkElements?: boolean): AnyNilable[]", function() {
    
    });
    describe("Testing function asErrorLike(obj?: TDefined): Nilable<ErrorLike>", function() {
    
    });
});